"""Generate encounter-level monster damage details with simple modifiers.

Input is the action report generated by generate_monster_encounter_turn_actions.py.
The numeric model applies directly parsed Strength and player Vulnerable:

    adjusted = (asc10DamagePerHit + currentMonsterStrength) * hitCount
    if player has Vulnerable: adjusted *= 1.5

Vulnerable is ticked down at enemy-side turn end, matching VulnerablePower.
Other monster-specific powers are recorded in an appendix instead of being
folded into the numeric damage table.
"""

from __future__ import annotations

import argparse
import datetime as dt
import itertools
import json
import math
from collections import defaultdict
from pathlib import Path
from typing import Any


VULNERABLE_MULTIPLIER = 1.5


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate per-encounter per-turn monster damage details."
    )
    parser.add_argument(
        "--actions",
        default="data/generated/monster_encounter_turn_actions.generated.json",
        help="Action report from generate_monster_encounter_turn_actions.py.",
    )
    parser.add_argument(
        "--decompile-root",
        default="data/generated/decompiled/sts2",
        help="ILSpy decompiled source root, used for modifier appendix hints.",
    )
    parser.add_argument(
        "--output-json",
        default="data/generated/monster_encounter_damage_details.generated.json",
        help="Output JSON path.",
    )
    parser.add_argument(
        "--output-md",
        default="data/generated/monster_encounter_damage_details.md",
        help="Output Markdown path.",
    )
    return parser.parse_args()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def round3(value: float) -> float:
    if math.isclose(value, 0.0, abs_tol=0.0005):
        return 0.0
    return round(value, 3)


def fmt(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        value = round3(value)
        if value.is_integer():
            return str(int(value))
        return f"{value:g}"
    return str(value)


def escape_md(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def format_bilingual_name(name: dict[str, Any] | None, fallback: str = "") -> str:
    if not isinstance(name, dict):
        return fallback
    english = name.get("en") or fallback
    chinese = name.get("zh") or fallback
    if english and chinese:
        return f"{chinese} / {english}"
    return chinese or english or fallback


def format_monster(monster_type: str, name: dict[str, Any] | None) -> str:
    return format_bilingual_name(name, monster_type)


def format_intents(intent_details: list[dict[str, Any]]) -> str:
    return ",".join(format_bilingual_name(intent, intent.get("id", "")) for intent in intent_details)


def power_source_path(decompile_root: Path, power_name: str) -> Path | None:
    candidates = list(decompile_root.rglob(f"{power_name}Power.cs"))
    return candidates[0] if candidates else None


def power_source_has_damage_hooks(decompile_root: Path, power_name: str) -> tuple[bool, str]:
    path = power_source_path(decompile_root, power_name)
    if path is None:
        return False, "power source not found"
    source = path.read_text(encoding="utf-8", errors="replace")
    tokens = [
        "ModifyDamage",
        "AfterDamageGiven",
        "BeforeDamageReceived",
        "AfterDamageReceived",
        "CreatureCmd.Damage",
        "DamageCmd",
        "StrengthPower",
    ]
    matched = [token for token in tokens if token in source]
    if matched:
        return True, ", ".join(matched)
    return False, "no direct damage hook token found"


def act_label(encounter: dict[str, Any]) -> str:
    acts = encounter.get("acts", [])
    if not acts:
        return ""
    return ",".join(f"{act.get('actTypeName')}({act.get('actNumber')})" for act in acts)


def state_attacks(state: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        action
        for action in state.get("categories", {}).get("attack", [])
        if action.get("kind") == "attack"
    ]


def attack_base_damage(attack: dict[str, Any]) -> tuple[float | None, str | None]:
    amount = attack.get("ascensionAmount")
    hits = attack.get("ascensionHitCount")
    if amount is None:
        return None, attack.get("amountExpression") or attack.get("kind")
    if hits is None:
        hits = 1
    return float(amount) * float(hits), None


def state_base_damage(state: dict[str, Any]) -> tuple[float, list[str]]:
    total = 0.0
    unknown: list[str] = []
    for attack in state_attacks(state):
        damage, expression = attack_base_damage(attack)
        if damage is None:
            unknown.append(expression or "unknown")
        else:
            total += damage
    return total, unknown


def adjusted_attack_damage(
    attack: dict[str, Any],
    strength: float,
    vulnerable_active: bool,
) -> tuple[float | None, str | None]:
    amount = attack.get("ascensionAmount")
    hits = attack.get("ascensionHitCount")
    if amount is None:
        return None, attack.get("amountExpression") or attack.get("kind")
    if hits is None:
        hits = 1
    damage = (float(amount) + strength) * float(hits)
    if vulnerable_active:
        damage *= VULNERABLE_MULTIPLIER
    return damage, None


def state_adjusted_damage(
    state: dict[str, Any],
    strength: float,
    vulnerable_duration: float,
) -> tuple[float, list[str]]:
    total = 0.0
    unknown: list[str] = []
    vulnerable_active = vulnerable_duration > 0
    for attack in state_attacks(state):
        damage, expression = adjusted_attack_damage(attack, strength, vulnerable_active)
        if damage is None:
            unknown.append(expression or "unknown")
        else:
            total += damage
    return total, unknown


def strength_gain_from_state(state: dict[str, Any]) -> tuple[float, list[dict[str, Any]]]:
    total = 0.0
    events: list[dict[str, Any]] = []
    for action in state.get("categories", {}).get("selfBuff", []):
        parameter = action.get("parameter")
        kind = action.get("kind")
        if kind == "buffStrength" or parameter == "power:Strength":
            amount = action.get("ascensionAmount")
            if amount is None:
                amount = action.get("amount")
            target = action.get("target")
            applied = target == "self" and amount is not None
            if applied and amount is not None:
                total += float(amount)
            events.append(
                {
                    "modifier": "Strength",
                    "amount": amount,
                    "target": target,
                    "appliedInDamageModel": applied,
                    "note": "Adds to this monster's future powered attack damage per hit."
                    if applied
                    else "Strength amount or target is unresolved; recorded but not applied.",
                }
            )
    return total, events


def vulnerable_gain_from_state(state: dict[str, Any]) -> tuple[float, list[dict[str, Any]]]:
    total = 0.0
    events: list[dict[str, Any]] = []
    for action in state.get("categories", {}).get("playerDebuff", []):
        parameter = action.get("parameter")
        kind = action.get("kind")
        if kind == "debuffVulnerable" or parameter == "power:Vulnerable":
            amount = action.get("ascensionAmount")
            if amount is None:
                amount = action.get("amount")
            applied = amount is not None
            if applied:
                total += float(amount)
            events.append(
                {
                    "modifier": "Vulnerable",
                    "amount": amount,
                    "target": action.get("target"),
                    "appliedInDamageModel": applied,
                    "note": "Player takes 1.5x powered attack damage while active.",
                }
            )
    return total, events


def other_power_events(state: dict[str, Any]) -> list[dict[str, Any]]:
    events: list[dict[str, Any]] = []
    for category in ("selfBuff", "playerDebuff"):
        for action in state.get("categories", {}).get(category, []):
            parameter = action.get("parameter")
            if not parameter or not parameter.startswith("power:"):
                continue
            power_name = parameter.split(":", 1)[1]
            if power_name in {"Strength", "Vulnerable", "Weak", "Frail"}:
                continue
            events.append(
                {
                    "modifier": power_name,
                    "category": category,
                    "amount": action.get("ascensionAmount") if action.get("ascensionAmount") is not None else action.get("amount"),
                    "target": action.get("target"),
                    "appliedInDamageModel": False,
                    "note": "Recorded as a monster-specific power; not folded into the simple Strength/Vulnerable damage model.",
                }
            )
    return events


def monster_turn_states(
    monster_turns: dict[str, list[dict[str, Any]]],
    monster_type: str,
    turn_number: int,
) -> list[dict[str, Any]]:
    turns = monster_turns.get(monster_type, [])
    if turn_number - 1 >= len(turns):
        return []
    states = turns[turn_number - 1].get("states", [])
    return states


def slot_possible_types(slot: dict[str, Any]) -> list[str]:
    if slot.get("monsterTypeName"):
        return [slot["monsterTypeName"]]
    return slot.get("possibleMonsterTypeNames", [])


def composition_scenarios(slots: list[dict[str, Any]]) -> list[tuple[tuple[str, ...], float]]:
    choices = [slot_possible_types(slot) or ["<missing>"] for slot in slots]
    total = math.prod(len(choice) for choice in choices)
    if total <= 0:
        return []
    probability = 1.0 / total
    return [(tuple(types), probability) for types in itertools.product(*choices)]


DistributionKey = tuple[tuple[str, ...], float, tuple[float, ...]]


def aggregate_distribution(
    distribution: dict[DistributionKey, float]
) -> dict[DistributionKey, float]:
    result: dict[DistributionKey, float] = defaultdict(float)
    for (composition, vulnerable, strengths), probability in distribution.items():
        key = (composition, round3(vulnerable), tuple(round3(value) for value in strengths))
        result[key] += probability
    return dict(result)


def add_detail(
    details: dict[tuple[int, str, str], dict[str, Any]],
    slot_position: int,
    monster_type: str,
    monster_name: dict[str, Any] | None,
    state: dict[str, Any],
    probability: float,
    base_damage: float,
    adjusted_damage: float,
    strength_before: float,
    vulnerable_duration_before: float,
    unknown_damage: list[str],
    strength_gain: float,
    vulnerable_gain: float,
) -> None:
    key = (slot_position, monster_type, state.get("stateId", ""))
    detail = details.setdefault(
        key,
        {
            "slotPosition": slot_position,
            "monsterTypeName": monster_type,
            "monsterName": monster_name,
            "stateId": state.get("stateId"),
            "intents": state.get("intents", []),
            "intentDetails": state.get("intentDetails", []),
            "probability": 0.0,
            "expectedBaseDamage": 0.0,
            "expectedAdjustedDamage": 0.0,
            "averageStrengthBefore": 0.0,
            "vulnerableActiveProbabilityBefore": 0.0,
            "averageVulnerableDurationBefore": 0.0,
            "expectedStrengthGain": 0.0,
            "expectedVulnerableGain": 0.0,
            "unknownDamageExpressions": set(),
            "categoryIds": state.get("categoryIds", []),
        },
    )
    detail["probability"] += probability
    detail["expectedBaseDamage"] += probability * base_damage
    detail["expectedAdjustedDamage"] += probability * adjusted_damage
    detail["averageStrengthBefore"] += probability * strength_before
    detail["vulnerableActiveProbabilityBefore"] += probability * (1.0 if vulnerable_duration_before > 0 else 0.0)
    detail["averageVulnerableDurationBefore"] += probability * vulnerable_duration_before
    detail["expectedStrengthGain"] += probability * strength_gain
    detail["expectedVulnerableGain"] += probability * vulnerable_gain
    for expression in unknown_damage:
        detail["unknownDamageExpressions"].add(expression)


def finalize_detail(detail: dict[str, Any]) -> dict[str, Any]:
    probability = detail["probability"]
    normalized = dict(detail)
    if probability > 0:
        normalized["averageStrengthBefore"] = detail["averageStrengthBefore"] / probability
        normalized["vulnerableActiveProbabilityBefore"] = detail["vulnerableActiveProbabilityBefore"] / probability
        normalized["averageVulnerableDurationBefore"] = detail["averageVulnerableDurationBefore"] / probability
    normalized["probability"] = round3(probability)
    for key in (
        "expectedBaseDamage",
        "expectedAdjustedDamage",
        "averageStrengthBefore",
        "vulnerableActiveProbabilityBefore",
        "averageVulnerableDurationBefore",
        "expectedStrengthGain",
        "expectedVulnerableGain",
    ):
        normalized[key] = round3(normalized[key])
    normalized["unknownDamageExpressions"] = sorted(normalized["unknownDamageExpressions"])
    return normalized


def collect_state_modifier_events(
    monster_type: str,
    monster_name: dict[str, Any] | None,
    state: dict[str, Any],
    decompile_root: Path,
) -> list[dict[str, Any]]:
    strength_gain, strength_events = strength_gain_from_state(state)
    vulnerable_gain, vulnerable_events = vulnerable_gain_from_state(state)
    events = strength_events + vulnerable_events + other_power_events(state)
    result: list[dict[str, Any]] = []
    for event in events:
        modifier = event["modifier"]
        extra_note = ""
        if modifier not in {"Strength", "Vulnerable"}:
            has_hook, reason = power_source_has_damage_hooks(decompile_root, modifier)
            extra_note = f" Power source scan: {reason}."
            if has_hook:
                event = event | {"damageRelevantCandidate": True}
            else:
                event = event | {"damageRelevantCandidate": False}
        result.append(
            {
                "monsterTypeName": monster_type,
                "monsterName": monster_name,
                "stateId": state.get("stateId"),
                "intents": state.get("intents", []),
                "intentDetails": state.get("intentDetails", []),
                "moveMethod": state.get("moveMethod"),
                "modifier": modifier,
                "amount": event.get("amount"),
                "target": event.get("target"),
                "appliedInDamageModel": event.get("appliedInDamageModel", False),
                "damageRelevantCandidate": event.get("damageRelevantCandidate", modifier in {"Strength", "Vulnerable"}),
                "note": event.get("note", "") + extra_note,
                "strengthGainIfApplied": strength_gain if modifier == "Strength" else 0,
                "vulnerableGainIfApplied": vulnerable_gain if modifier == "Vulnerable" else 0,
            }
        )
    return result


def simulate_encounter(
    encounter: dict[str, Any],
    monster_turns: dict[str, list[dict[str, Any]]],
    monster_names: dict[str, dict[str, Any]],
    turn_count: int,
) -> dict[str, Any]:
    slots = encounter.get("monsterSlots", [])
    scenarios = composition_scenarios(slots)
    distribution: dict[DistributionKey, float] = {}
    # The distribution key is (fixed slot composition, player vulnerable duration,
    # per-slot monster strength).
    for composition, probability in scenarios:
        distribution[(composition, 0.0, tuple(0.0 for _ in slots))] = probability

    turns: list[dict[str, Any]] = []
    for turn_number in range(1, turn_count + 1):
        start_vulnerable_active = sum(
            probability for (_, vulnerable, _), probability in distribution.items() if vulnerable > 0
        )
        start_vulnerable_duration = sum(
            probability * vulnerable for (_, vulnerable, _), probability in distribution.items()
        )
        working_distribution: dict[DistributionKey, float] = distribution
        slot_details_by_position: dict[int, dict[tuple[int, str, str], dict[str, Any]]] = {
            int(slot.get("position", index + 1)): {}
            for index, slot in enumerate(slots)
        }
        slot_totals: dict[int, dict[str, Any]] = {
            int(slot.get("position", index + 1)): {
                "expectedBaseDamage": 0.0,
                "expectedAdjustedDamage": 0.0,
                "unknownDamageExpressions": set(),
                "expectedStrengthGain": 0.0,
                "expectedVulnerableGain": 0.0,
            }
            for index, slot in enumerate(slots)
        }

        for slot_index, slot in enumerate(slots):
            position = int(slot.get("position", slot_index + 1))
            next_distribution: dict[DistributionKey, float] = defaultdict(float)
            for (composition, vulnerable, strengths), branch_probability in working_distribution.items():
                monster_type = composition[slot_index] if slot_index < len(composition) else "<missing>"
                monster_name = monster_names.get(monster_type)
                states = monster_turn_states(monster_turns, monster_type, turn_number)
                if not states:
                    next_distribution[(composition, vulnerable, strengths)] += branch_probability
                    continue
                state_probability = 1.0 / len(states)
                for state in states:
                    probability = branch_probability * state_probability
                    strength_before = strengths[slot_index]
                    base_damage, base_unknown = state_base_damage(state)
                    adjusted_damage, adjusted_unknown = state_adjusted_damage(
                        state,
                        strength_before,
                        vulnerable,
                    )
                    unknown_damage = sorted(set(base_unknown + adjusted_unknown))
                    strength_gain, _ = strength_gain_from_state(state)
                    vulnerable_gain, _ = vulnerable_gain_from_state(state)

                    add_detail(
                        slot_details_by_position[position],
                        position,
                        monster_type,
                        monster_name,
                        state,
                        probability,
                        base_damage,
                        adjusted_damage,
                        strength_before,
                        vulnerable,
                        unknown_damage,
                        strength_gain,
                        vulnerable_gain,
                    )
                    slot_totals[position]["expectedBaseDamage"] += probability * base_damage
                    slot_totals[position]["expectedAdjustedDamage"] += probability * adjusted_damage
                    slot_totals[position]["expectedStrengthGain"] += probability * strength_gain
                    slot_totals[position]["expectedVulnerableGain"] += probability * vulnerable_gain
                    for expression in unknown_damage:
                        slot_totals[position]["unknownDamageExpressions"].add(expression)

                    new_strengths = list(strengths)
                    new_strengths[slot_index] += strength_gain
                    new_vulnerable = vulnerable + vulnerable_gain
                    next_distribution[(composition, new_vulnerable, tuple(new_strengths))] += probability
            working_distribution = aggregate_distribution(next_distribution)

        end_distribution: dict[DistributionKey, float] = defaultdict(float)
        for (composition, vulnerable, strengths), probability in working_distribution.items():
            end_distribution[(composition, max(0.0, vulnerable - 1.0), strengths)] += probability
        distribution = aggregate_distribution(end_distribution)

        slot_reports = []
        for index, slot in enumerate(slots):
            position = int(slot.get("position", index + 1))
            details = [
                finalize_detail(detail)
                for detail in slot_details_by_position[position].values()
            ]
            details.sort(key=lambda item: (item["monsterTypeName"], item["stateId"] or ""))
            totals = slot_totals[position]
            slot_reports.append(
                {
                    "position": position,
                    "slotName": slot.get("slotName"),
                    "monsterTypeName": slot.get("monsterTypeName"),
                    "possibleMonsterTypeNames": slot_possible_types(slot),
                    "possibleMonsterNames": [
                        {
                            "typeName": monster_type,
                            "name": monster_names.get(monster_type),
                        }
                        for monster_type in slot_possible_types(slot)
                    ],
                    "expectedBaseDamage": round3(totals["expectedBaseDamage"]),
                    "expectedAdjustedDamage": round3(totals["expectedAdjustedDamage"]),
                    "expectedStrengthGain": round3(totals["expectedStrengthGain"]),
                    "expectedVulnerableGain": round3(totals["expectedVulnerableGain"]),
                    "unknownDamageExpressions": sorted(totals["unknownDamageExpressions"]),
                    "details": details,
                }
            )

        turns.append(
            {
                "turn": turn_number,
                "playerVulnerableActiveProbabilityAtStart": round3(start_vulnerable_active),
                "expectedPlayerVulnerableDurationAtStart": round3(start_vulnerable_duration),
                "totalBaseDamage": round3(sum(slot["expectedBaseDamage"] for slot in slot_reports)),
                "totalAdjustedDamage": round3(sum(slot["expectedAdjustedDamage"] for slot in slot_reports)),
                "unknownDamageExpressions": sorted(
                    {
                        expression
                        for slot in slot_reports
                        for expression in slot["unknownDamageExpressions"]
                    }
                ),
                "slots": slot_reports,
            }
        )

    return {
        "modelId": encounter.get("modelId"),
        "typeName": encounter.get("typeName"),
        "acts": encounter.get("acts", []),
        "actLabel": act_label(encounter),
        "category": encounter.get("category"),
        "hasConditionalMonsterSelection": encounter.get("hasConditionalMonsterSelection"),
        "warnings": encounter.get("warnings", []),
        "turns": turns,
        "compositionAssumption": "Conditional/random monster slots are treated as equally likely candidates.",
    }


def build_modifier_appendix(
    action_report: dict[str, Any],
    monster_names: dict[str, dict[str, Any]],
    decompile_root: Path,
) -> list[dict[str, Any]]:
    rows: dict[tuple[str, str, str, Any, str], dict[str, Any]] = {}
    for monster in action_report.get("monsterCatalog", []):
        monster_type = monster.get("typeName")
        for move in monster.get("moves", []):
            for event in collect_state_modifier_events(
                monster_type,
                monster_names.get(monster_type),
                move,
                decompile_root,
            ):
                key = (
                    event["monsterTypeName"],
                    event["stateId"],
                    event["modifier"],
                    event.get("amount"),
                    event.get("target") or "",
                )
                rows[key] = event
    return sorted(
        rows.values(),
        key=lambda item: (
            not item.get("appliedInDamageModel"),
            item["modifier"],
            item["monsterTypeName"],
            item["stateId"] or "",
        ),
    )


def build_report(action_report: dict[str, Any], decompile_root: Path) -> dict[str, Any]:
    monster_turns = {
        monster["typeName"]: monster.get("turns", [])
        for monster in action_report.get("monsterCatalog", [])
    }
    monster_names = {
        monster["typeName"]: monster.get("name")
        for monster in action_report.get("monsterCatalog", [])
    }
    turn_count = int(action_report.get("turnCount", 14))
    encounters = [
        simulate_encounter(encounter, monster_turns, monster_names, turn_count)
        for encounter in action_report.get("encounters", [])
    ]
    modifier_appendix = build_modifier_appendix(action_report, monster_names, decompile_root)
    unknown_encounters = sum(
        1
        for encounter in encounters
        if any(turn["unknownDamageExpressions"] for turn in encounter["turns"])
    )
    return {
        "schemaVersion": 1,
        "generatedAt": dt.datetime.now(dt.timezone.utc).isoformat(),
        "sourceFiles": {
            "turnActions": action_report.get("sourceFiles", {}),
            "actionReport": "data/generated/monster_encounter_turn_actions.generated.json",
            "decompileRoot": str(decompile_root),
        },
        "turnCount": turn_count,
        "damageBasis": "Ascension 10 attack values when available.",
        "nameLocalization": action_report.get("nameLocalization", {}),
        "intentNames": action_report.get("intentNames", {}),
        "modifierRules": [
            "StrengthPower adds current Strength to each powered attack hit by that monster.",
            "VulnerablePower multiplies powered attack damage received by the player by 1.5 while active.",
            "VulnerablePower ticks down at enemy-side turn end, so same-turn later monster slots can benefit from newly applied Vulnerable, then duration decreases by 1.",
            "Other monster-specific powers are recorded in the modifier appendix but are not included in numeric adjusted damage.",
            "Conditional/random monster slots and unknown initial move states use equal-weight candidates/states, matching the action table approximation.",
        ],
        "summary": {
            "encounterCount": len(encounters),
            "turnCount": turn_count,
            "modifierAppendixRows": len(modifier_appendix),
            "encountersWithUnknownDynamicDamage": unknown_encounters,
        },
        "encounters": encounters,
        "modifierAppendix": modifier_appendix,
    }


def detail_text(detail: dict[str, Any]) -> str:
    unknown = ""
    if detail["unknownDamageExpressions"]:
        unknown = " unknown=" + ",".join(detail["unknownDamageExpressions"])
    intents = ""
    if detail.get("intentDetails"):
        intents = " intents=" + format_intents(detail["intentDetails"])
    modifiers = []
    if detail["averageStrengthBefore"]:
        modifiers.append(f"str {fmt(detail['averageStrengthBefore'])}")
    if detail["vulnerableActiveProbabilityBefore"]:
        modifiers.append(f"vulnP {fmt(detail['vulnerableActiveProbabilityBefore'])}")
    if detail["expectedStrengthGain"]:
        modifiers.append(f"+str {fmt(detail['expectedStrengthGain'])}")
    if detail["expectedVulnerableGain"]:
        modifiers.append(f"+vuln {fmt(detail['expectedVulnerableGain'])}")
    modifier_text = f" ({', '.join(modifiers)})" if modifiers else ""
    return (
        f"{format_monster(detail['monsterTypeName'], detail.get('monsterName'))}:{detail['stateId']} "
        f"p={fmt(detail['probability'])} base={fmt(detail['expectedBaseDamage'])} "
        f"adj={fmt(detail['expectedAdjustedDamage'])}{modifier_text}{intents}{unknown}"
    )


def write_markdown(report: dict[str, Any], path: Path) -> None:
    lines: list[str] = []
    lines.append("# Monster Encounter Damage Details")
    lines.append("")
    lines.append(f"Generated at: {report['generatedAt']}")
    lines.append(f"Turns: 1-{report['turnCount']}")
    lines.append("")
    lines.append("## Rules")
    lines.append("")
    for rule in report["modifierRules"]:
        lines.append(f"- {rule}")
    if report.get("nameLocalization"):
        lines.append("")
        lines.append("Name localization:")
        for key, value in report["nameLocalization"].items():
            lines.append(f"- {key}: {value}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| --- | ---: |")
    for key, value in report["summary"].items():
        lines.append(f"| {key} | {value} |")
    lines.append("")

    lines.append("## Encounter Turn Totals")
    lines.append("")
    lines.append("| Act | Category | Encounter | Conditional | Turn | Base damage | Adjusted damage | Vuln active P(start) | Vuln duration E(start) | Unknown dynamic damage |")
    lines.append("| --- | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | --- |")
    for encounter in report["encounters"]:
        for turn in encounter["turns"]:
            lines.append(
                "| "
                + " | ".join(
                    [
                        escape_md(encounter["actLabel"]),
                        escape_md(encounter["category"]),
                        escape_md(encounter["typeName"]),
                        "yes" if encounter["hasConditionalMonsterSelection"] else "no",
                        str(turn["turn"]),
                        fmt(turn["totalBaseDamage"]),
                        fmt(turn["totalAdjustedDamage"]),
                        fmt(turn["playerVulnerableActiveProbabilityAtStart"]),
                        fmt(turn["expectedPlayerVulnerableDurationAtStart"]),
                        escape_md(",".join(turn["unknownDamageExpressions"])),
                    ]
                )
                + " |"
            )
    lines.append("")

    lines.append("## Slot Damage Details")
    lines.append("")
    lines.append("| Act | Category | Encounter | Turn | Slot | Monster candidates (ZH / EN) | Base | Adjusted | Strength gain | Vulnerable gain | State details |")
    lines.append("| --- | --- | --- | ---: | --- | --- | ---: | ---: | ---: | ---: | --- |")
    for encounter in report["encounters"]:
        for turn in encounter["turns"]:
            for slot in turn["slots"]:
                state_details = "<br>".join(detail_text(detail) for detail in slot["details"])
                slot_name = slot.get("slotName") or f"slot{slot['position']}"
                candidates = ",".join(
                    format_monster(item["typeName"], item.get("name"))
                    for item in slot.get("possibleMonsterNames", [])
                )
                lines.append(
                    "| "
                    + " | ".join(
                        [
                            escape_md(encounter["actLabel"]),
                            escape_md(encounter["category"]),
                            escape_md(encounter["typeName"]),
                            str(turn["turn"]),
                            escape_md(slot_name),
                            escape_md(candidates),
                            fmt(slot["expectedBaseDamage"]),
                            fmt(slot["expectedAdjustedDamage"]),
                            fmt(slot["expectedStrengthGain"]),
                            fmt(slot["expectedVulnerableGain"]),
                            escape_md(state_details),
                        ]
                    )
                    + " |"
                )
    lines.append("")

    lines.append("## Damage Modifier Appendix")
    lines.append("")
    lines.append("| Applied | Candidate | Monster (ZH / EN) | State | Modifier | Amount | Target | Note |")
    lines.append("| --- | --- | --- | --- | --- | ---: | --- | --- |")
    for row in report["modifierAppendix"]:
        lines.append(
            "| "
            + " | ".join(
                [
                    "yes" if row["appliedInDamageModel"] else "no",
                    "yes" if row["damageRelevantCandidate"] else "no",
                    escape_md(format_monster(row["monsterTypeName"], row.get("monsterName"))),
                    escape_md(row["stateId"]),
                    escape_md(row["modifier"]),
                    fmt(row.get("amount")),
                    escape_md(row.get("target") or ""),
                    escape_md(row["note"]),
                ]
            )
            + " |"
        )
    lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append("- Base damage is the parsed Ascension 10 attack damage before Strength/Vulnerable.")
    lines.append("- Adjusted damage includes parsed self Strength and player Vulnerable only.")
    lines.append("- Unknown dynamic damage expressions are carried through instead of guessed.")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    action_path = Path(args.actions)
    if not action_path.exists():
        raise FileNotFoundError(
            f"Missing action report at {action_path}. Run generate_monster_encounter_turn_actions.py first."
        )
    action_report = load_json(action_path)
    report = build_report(action_report, Path(args.decompile_root))
    output_json = Path(args.output_json)
    output_md = Path(args.output_md)
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_md.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(
        json.dumps(report, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    write_markdown(report, output_md)
    print("monster encounter damage details generated")
    print(f"encounters: {report['summary']['encounterCount']}")
    print(f"turns: 1-{report['turnCount']}")
    print(f"modifierAppendixRows: {report['summary']['modifierAppendixRows']}")
    print(f"unknownDynamicDamageEncounters: {report['summary']['encountersWithUnknownDynamicDamage']}")
    print(f"output: {output_json}")
    print(f"report: {output_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
